* About

[[https://github.com/jakub-stastny/blog.custom-elements.org/actions/workflows/test.yml][https://github.com/jakub-stastny/blog.custom-elements.org/actions/workflows/test.yml/badge.svg]]

Provides =org-mode= [[https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements][custom element]], which allows us to display Org mode formatted text as HTML.

Org mode format is used in the =body= field of the generated blog posts.

It uses [[https://github.com/jakub-stastny/blog.parser.post.org][blog.parser.post.org]] compiled to WebAssembly in order to have a consistent parser output (by using different Org mode parsers we might run into incompatibilities, which is undesirable).

Custom elements can be [[https://guide.elm-lang.org/interop/custom_elements.html][integrated into Elm]], which is how we make use of this in the [[https://github.com/jakub-stastny/blog.engine][blog.engine]].

*** Example

#+BEGIN_SRC html
  <article>
    <h1>Hello world!</h1>
    <p class="excerpt">
      Let's blog again!
    </p>

    <org-mode>
      * So what is it going to be about?

      - Programming.
      - Life.
    </org-mode>
  </article>
#+END_SRC

* Resources and community

This repository is only one of many packages that I wrote for my blog. For the overall architecture and documentation please see the [[https://github.com/jakub-stastny/blog.meta][blog meta repo]]. That's also the place to [[https://github.com/jakub-stastny/blog.meta/issues][raise any issues]] if you encounter any and to [[https://github.com/jakub-stastny/blog.meta/discussions][discuss the project and ask questions]].

* Understanding the code base

/Where's all the source code?/

** Literate programming

In case you're wondering where are all the Elm files, you have to tangle code blocks from [[https://orgmode.org][Org mode]] files in =src= into actual Elm files using Org mode in Emacs.

Don't worry about it though – unless you want to set up the code locally, there is no need. Just read the Org mode files in the =src= directory, it contains well-documented code.

If you're curious why am I doing this, you can check my post on [[https://github.com/jakub-stastny/blog.meta/blob/master/doc/literate-programming.org][literate programming]].

* Setup

If you want to contribute or just play around with it, check out [[https://github.com/jakub-stastny/blog.meta/blob/master/doc/setup.org][how to set up the repository]].
